import os

for dir in os.listdir():
    print(dir)
for dir in os.listdir():
    print(os.path.isdir(dir))
    print()
    print(dir)
    print()
    print(os.path.isdir(dir))
    print()
    print(os.stat(dir).st_mode)
    print()
    print(os.stat(dir).st_size)
    print()
    print(os.stat(dir).st_mtime)
    print()
    print(os.stat(dir).st_uid)
    print()
    print(os.stat(dir).st_gid)
    print()
    print(os.path.isdir(dir))
    print()
    print(dir)
    print()
    print(os.path.isdir(dir))
    print()
    print(os.stat(dir).st_mode)
    print()
    print(os.stat(dir).st_size)
    print()
    print(os.stat(dir).st_mtime)
    print()
    print(os.stat(dir).st_uid)
    print()
    print(os.stat(dir).st_gid)
    print()
